version: '2'

services:
  postgres:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  django:
    build: .
    links:
      - postgres
    volumes:
      - /app/static/

  nginx:
    image: nginx
    links:
      - django
    ports:
        - "8000:80"
    volumes_from:
      - "django:ro"
    volumes:
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
