# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Protein'), (1, 'Publication'), (2, 'Qualifier'), (3, 'Go term'), (4, 'Evidence'), (5, 'Originality')], default=0, max_length=11)),
                ('notes', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', uuidfield.fields.UUIDField(blank=True, editable=False, max_length=32, unique=True)),
                ('entry_type', models.IntegerField(choices=[(0, 'Private'), (1, 'Public'), (2, 'Challenge')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Annotation')),
            ],
        ),
        migrations.CreateModel(
            name='GAF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(max_length=64)),
                ('db_object_id', models.CharField(max_length=64)),
                ('db_object_symbol', models.CharField(max_length=64)),
                ('qualifier', models.CharField(max_length=64)),
                ('go_id', models.CharField(max_length=64)),
                ('db_reference', models.CharField(max_length=64)),
                ('evidence_code', models.CharField(max_length=64)),
                ('with_or_from', models.CharField(max_length=64)),
                ('aspect', models.CharField(max_length=64)),
                ('db_object_name', models.CharField(max_length=64)),
                ('db_object_synonym', models.CharField(max_length=64)),
                ('db_object_type', models.CharField(max_length=64)),
                ('taxon', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('assigned_by', models.CharField(max_length=64)),
                ('annotation_extension', models.CharField(max_length=64)),
                ('gene_product_id', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='gaf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.GAF'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Challenge'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='gaf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.GAF'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
