# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotation',
            name='gaf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.GAF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
