# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_strand', models.CharField(max_length=64)),
                ('end_strand', models.CharField(max_length=64)),
                ('ebi_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=128)),
                ('alternate_name', models.CharField(max_length=128)),
                ('taxon', models.CharField(max_length=64)),
                ('ebi_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organism'),
        ),
    ]
