# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160830_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='end_strand',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='start_strand',
        ),
        migrations.AddField(
            model_name='gene',
            name='end',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gene',
            name='strand',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gene',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organism',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
