# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160219_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='gaf',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.GAF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='gaf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.GAF'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
