# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pages',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
