# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-08 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160901_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaf',
            name='aspect',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
