# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160220_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Annotation'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Challenge'),
        ),
    ]
