# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160220_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
