# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20160711_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaf',
            name='annotation_extension',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='db_object_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='db_object_synonym',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='gene_product_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='qualifier',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='with_or_from',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
