# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170208_1725'),
        ('base', '0005_auto_20170227_2138'),
    ]

    operations = [
    ]
