# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160224_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaf',
            old_name='Qualifier',
            new_name='qualifier',
        ),
    ]
