# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20160712_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaf',
            name='annotation_extension',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='db_object_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='db_object_synonym',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='gene_product_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='with_or_from',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
