# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20160224_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaf',
            name='date',
            field=models.DateField(),
        ),
    ]
