# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_auto_20160309_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaf',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gaf', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
