# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-14 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20160714_1617'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gaf',
            unique_together=set([('db', 'db_object_id', 'go_id', 'db_reference', 'evidence_code')]),
        ),
    ]
