# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_gaf_review_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaf',
            name='review_state',
            field=models.IntegerField(choices=[(0, 'External'), (1, 'Unreviewed'), (2, 'Accepted'), (3, 'Rejected')], default=0, null=True),
        ),
    ]
