# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160721_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
