# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20160722_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gaf',
            name='id',
        ),
        migrations.AddField(
            model_name='assessment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gaf',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
