# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 18:03
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20160722_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='flagged',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Protein'), (1, 'Publication'), (2, 'Qualifier'), (3, 'Go term'), (4, 'Evidence'), (5, 'Originality')], max_length=11),
        ),
    ]
