# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20160722_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaf',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
