# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20160727_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='flagged',
            field=models.TextField(blank=True, null=True),
        ),
    ]
