# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20160727_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='gaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='base.GAF'),
        ),
    ]
