# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20160803_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaf',
            name='superseded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.GAF'),
        ),
    ]
