# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20160803_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Challenge'),
        ),
    ]
