# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_assessment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
