# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20160804_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaf',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
