# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20160818_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaf',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
